// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param displayName 
 * @param permissions 
 * @param requestCount 
 * @param warnings 
 */
@Serializable

data class PostAuthLocal200Response (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "displayName")
    val displayName: kotlin.String? = null,

    @SerialName(value = "permissions")
    val permissions: kotlin.Double? = null,

    @SerialName(value = "requestCount")
    val requestCount: kotlin.Double? = null,

    @SerialName(value = "warnings")
    val warnings: kotlin.collections.List<kotlin.String>? = null

) {
    override fun toString(): String = "[REDACTED]"



}

